/// HuggingFace-compatible base streamer interface.
///
/// Defines the core API for streaming token decoders, matching HuggingFace's
/// `transformers.generation.streamers.BaseStreamer` interface.
///
/// Implementations should:
/// - Accept tokens via [put] as they are generated
/// - Signal completion via [end]
/// - Handle incomplete sequences appropriately
abstract class BaseStreamer {
  /// Add a token ID to the stream.
  ///
  /// Called for each token generated by the LLM. Implementations should
  /// accumulate tokens and emit decoded text when ready.
  ///
  /// In HuggingFace, this method accepts batches, but for typical Dart LLM
  /// use cases where tokens arrive one at a time, we accept a single token.
  void put(int tokenId);

  /// Signal the end of token generation.
  ///
  /// Called when the LLM has finished generating tokens. Implementations
  /// should flush any remaining buffered content and perform cleanup.
  void end();
}
